# -*- coding: utf-8 -*-
"""DS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idXTS5q5jy7aQZhaUeCtrp0fybQ8B_8I

# Data Loading
"""

import kagglehub

path = kagglehub.dataset_download("ankitverma2010/ecommerce-customer-churn-analysis-and-prediction")
print("Path to dataset files:", path)

import os
print(os.listdir(path))

# Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Loading data
file_path = os.path.join(path, 'E Commerce Dataset.xlsx')

xls = pd.ExcelFile(file_path)
print(xls.sheet_names)

df = pd.read_excel(file_path, sheet_name='E Comm')
print(df['Churn'].value_counts())
df.head()

"""#  Data Tidying & Cleaning"""

df.shape

df['Churn'].value_counts()

df.info()

df.columns

num_cols = [
    'Tenure',
    'WarehouseToHome',
    'HourSpendOnApp',
    'OrderAmountHikeFromlastYear',
    'CouponUsed',
    'OrderCount',
    'DaySinceLastOrder'
]
df[num_cols].describe().T

# Check missing values
missing_cols = df.isnull().sum()
missing_cols[missing_cols > 0]

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Handle missing values
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ['int64', 'float64']:
            df[col] = df[col].fillna(df[col].median())
        else:
            df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

# Final check
missing_after = df.isnull().sum()
print(missing_after[missing_after > 0])

# Chek duplication
df.duplicated().sum()

df['CityTier']  = df['CityTier'].astype('object')
df['Complain']  = df['Complain'].astype('object')
df['Churn'] = df['Churn'].astype(int)

# Compute outlier counts and percentages
results = []
for col in num_cols:
    series = df[col].dropna()
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outlier_mask = (series < lower) | (series > upper)
    count = outlier_mask.sum()
    pct = (count / series.count()) * 100
    results.append({
        'variable': col,
        'outlier_count': count,
        'outlier_pct': round(pct, 2)
    })

outlier_df = pd.DataFrame(results).sort_values(by='outlier_pct', ascending=False)
print(outlier_df.to_string(index=False))

# Handle Outliers
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
if 'Churn' in num_cols:
    num_cols.remove('Churn')

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.clip(df[col], lower, upper)

# Check inconsistent values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("-"*40)

# Handle inconsistent values
df['PreferredLoginDevice'] = df['PreferredLoginDevice'].replace({
    'Phone': 'Mobile Phone'
})
df['PreferredPaymentMode'] = df['PreferredPaymentMode'].replace({
    'COD': 'Cash on Delivery',
    'CC': 'Credit Card'
})
df['PreferedOrderCat'] = df['PreferedOrderCat'].replace({
    'Mobile Phone': 'Mobile'
})

# Check again inconsistent values
for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("-"*40)

# Categorical features
cat_features = [
    'PreferredPaymentMode',
    'PreferredLoginDevice',
    'Gender',
    'MaritalStatus',
    'PreferedOrderCat',
    'Complain'
]

print("\n========== CATEGORICAL FEATURES ==========\n")

for col in cat_features:
    print(f"\n===== {col} =====")

    df[col] = df[col].fillna('Unknown')
    result = df.groupby(col)['Churn'].mean().sort_values(ascending=False)

    print(result)
    print("-" * 40)

# Numerical features
num_features = [
    'OrderCount',
    'CashbackAmount',
    'Tenure',
    'DaySinceLastOrder'
]

print("\n========== NUMERICAL FEATURES (BINNED) ==========\n")

for col in num_features:
    print(f"\n===== {col} =====")

    binned = pd.cut(df[col], bins=4)

    result = df.pivot_table(values='Churn', index=binned, aggfunc='mean')
    result = result.sort_values(by='Churn', ascending=False)

    print(result)
    print("-" * 40)

"""# Feature Extraction"""

# Orders per tenure
df['OrdersPerTenure'] = df['OrderCount'] / (df['Tenure'] + 1)

"""This feature measures how active a customer is over their relationship duration with the company. It helps capture customer engagement over time."""

# Is Active Customer or not
df['IsActive'] = (df['DaySinceLastOrder'] < 10).astype(int)

"""This feature converts recency into a binary feature indicating whether a customer is currently active or inactive."""

# Recency level
import pandas as pd

df['RecencyLevel'] = pd.cut(
    df['DaySinceLastOrder'],
    bins=[0, 10, 30, 60, 1000],
    labels=[0, 1, 2, 3]
)

"""This feature groups customers based on how recently they interacted with the company, making the pattern easier for the model to learn."""

# Average order value
df['AvgOrderValue'] = df['CashbackAmount'] / (df['OrderCount'] + 1)

"""This feature shows the cashback received per order, reflecting customer engagement and spending efficiency."""

# Engagement Score
df['EngagementScore'] = df['OrderCount'] * df['CouponUsed']

"""This feature captures how actively customers use coupons while purchasing, reflecting engagement behavior.

# Feature Selection
"""

# Mutual Information
import pandas as pd
from sklearn.feature_selection import mutual_info_classif

# Encoding
X_sel = pd.get_dummies(df.drop('Churn', axis=1), drop_first=True).fillna(0)
y_sel = df['Churn']

mi_scores = mutual_info_classif(X_sel, y_sel, random_state=42)

mi_features = pd.Series(mi_scores, index=X_sel.columns)
mi_features = mi_features.sort_values(ascending=False)

print("Top Features (Mutual Information):")
print(mi_features.head(10))

# SelectKBest
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler
import pandas as pd


scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_sel)

selector = SelectKBest(score_func=chi2, k=10)
selector.fit(X_scaled, y_sel)

selected_features = X_sel.columns[selector.get_support()]

print(selected_features)

# Comparison
import pandas as pd

# SelectKBest results
kbest_features = selected_features

# Mutual Information results
mi_top = mi_features.head(10).index

common_features = list(set(kbest_features) & set(mi_top))
if len(common_features) == 0:
    common_features = list(mi_top)

print("Selected Features:", common_features)

# Comparison
import pandas as pd

# SelectKBest results
kbest_features = selected_features

kbest_df = pd.DataFrame({
   "Feature": kbest_features,
   "Selected_By": "SelectKBest (Chi2)"
})

# Mutual Information results
mi_top = mi_features.head(10).index

mi_df = pd.DataFrame({
   "Feature": mi_top,
   "Selected_By": "Mutual Information"
 })

common_features = list(set(kbest_features) & set(mi_top))
if len(common_features) == 0:
    common_features = list(mi_top)

print("Selected Features:", common_features)

comparison_df = pd.concat([kbest_df, mi_df], ignore_index=True)
comparison_df["In_Both"] = comparison_df["Feature"].isin(kbest_features) & comparison_df["Feature"].isin(mi_top)

print(comparison_df)

"""# Train-Test Split"""

df_model = df.copy()

# Train / Test Split
from sklearn.model_selection import train_test_split

X = pd.get_dummies(df.drop("Churn", axis=1), drop_first=True)
y = df["Churn"]

X = X.reindex(columns=common_features, fill_value=0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

import numpy as np

X_train = X_train.replace([np.inf, -np.inf], np.nan)
X_test = X_test.replace([np.inf, -np.inf], np.nan)

"""# Imbalance Handling & Modeling"""

# Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Check Imbalance
print("Train distribution:")
print(y_train.value_counts())

print("\nTrain ratio:")
print(y_train.value_counts(normalize=True))

# Model before imbalance handling
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("\n===== XGBoost (Before Imbalance Handling) =====\n")
print(classification_report(y_test, y_pred_xgb))

# Handle imbalance
neg = sum(y_train == 0)
pos = sum(y_train == 1)

scale_pos_weight = neg / pos

print("scale_pos_weight =", scale_pos_weight)

# Model after imbalance handling
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

xgb_model_bal = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# Train
xgb_model_bal.fit(X_train, y_train)

y_pred_proba = xgb_model_bal.predict_proba(X_test)[:, 1]

# Threshold tuning
threshold = 0.5
y_pred_xgb_bal = (y_pred_proba > threshold).astype(int)

# Evaluation
print("\n===== XGBoost (After Imbalance Handling) =====\n")
print(classification_report(y_test, y_pred_xgb_bal))

"""# Visualization"""

# Churn Distribution
sns.countplot(x='Churn', data=df)
plt.title("Churn Distribution")
plt.show()

# Churn vs Tenure
sns.boxplot(x='Churn', y='Tenure', data=df)
plt.title("Churn vs Tenure")
plt.show()

# Churn vs App Usage
sns.boxplot(x='Churn', y='HourSpendOnApp', data=df)
plt.title("Churn vs App Usage")
plt.show()

# Churn vs Preferred Login Device
sns.countplot(x='PreferredLoginDevice', hue='Churn', data=df)
plt.xticks(rotation=45)
plt.title("Login Device vs Churn")
plt.show()

# Churn vs Satisfaction Score
sns.boxplot(x='Churn', y='SatisfactionScore', data=df)
plt.title("Satisfaction vs Churn")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Tenure vs Cashback (Scatter Plot)
sns.scatterplot(x='Tenure', y='CashbackAmount', hue='Churn', data=df)
plt.title("Tenure vs Cashback")
plt.show()

# Cashback Distribution
sns.histplot(df['CashbackAmount'], kde=True)
plt.title("Cashback Distribution")
plt.show()

"""# Testing"""

import numpy as np

print("Enter customer details:\n")

tenure = float(input("Tenure: "))
city_tier = float(input("CityTier (1/2/3): "))
hour_spend = float(input("Hour Spend On App: "))
devices = float(input("Number Of Device Registered: "))
complain = float(input("Complain (0 or 1): "))
order_count = float(input("Order Count: "))
days_last_order = float(input("Day Since Last Order: "))

user_data = np.array([[
    tenure,
    city_tier,
    hour_spend,
    devices,
    complain,
    order_count,
    days_last_order
]])


proba = xgb_model_bal.predict_proba(user_data)[0][1]

threshold = 0.4
prediction = 1 if proba > threshold else 0

print("\n===== RESULT =====")
print("Churn Probability:", round(proba, 3))

if prediction == 1:
    print("HIGH risk of churn")
else:
    print("LOW risk of churn")